version: '3.8'

services:
  # Servicio de la aplicación
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
      - JWT_SECRET=tu_secreto_jwt_cambiame_en_produccion
    depends_on:
      - db
    restart: unless-stopped

  # Servicio de base de datos PostgreSQL
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

# Volúmenes persistentes
volumes:
  postgres_data: