version: '3.8'

services:
  # Servicio de la aplicación
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:mysql_password@db:3306/auth_db
      - JWT_SECRET=tu_secreto_jwt_cambiame_en_produccion
    depends_on:
      - db
    restart: unless-stopped

  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=auth_db
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

# Volúmenes persistentes
volumes:
  mysql_data: